### ISSUE TITLE
練習 10 學習 ngStyle 與 ngClass 建議寫法

### ISSUE THREAD

**Issue by doggy8088** [coolrare/ng12-cybersoft#10]
```css
.highlight {
  background-color: yellow;
}
```
